server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.171:3306/idm_test_zjyh_person?useUnicode\=true&characterEncoding\=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: rootpwd_commnet

  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/page/
      # 响应页面默认后缀
      suffix: .jsp
    # 静态资源路径
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**
